# Generated by Django 6.0.3 on 2026-09-20 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import inscricoes.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bolsas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("PENDENTE", "Pendente"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="RASCUNHO",
                        max_length=15,
                    ),
                ),
                ("termos_aceitos", models.BooleanField(default=False)),
                ("link_lattes", models.URLField(blank=True, default="")),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_envio", models.DateTimeField(blank=True, null=True)),
                ("data_cancelamento", models.DateTimeField(blank=True, null=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscricoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bolsa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscricoes",
                        to="bolsas.bolsa",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("HISTORICO_ESCOLAR", "Histórico Escolar"),
                            ("COMPROVANTE_MATRICULA", "Comprovante de Matrícula"),
                            ("ADICIONAL", "Documento adicional"),
                        ],
                        max_length=25,
                    ),
                ),
                ("nome_original", models.CharField(blank=True, default="", max_length=255)),
                ("arquivo", models.FileField(upload_to=inscricoes.models.caminho_documento)),
                ("enviado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="inscricoes.inscricao",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="inscricao",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "CANCELADA"), _negated=True),
                fields=("aluno", "bolsa"),
                name="uniq_inscricao_ativa_por_aluno_e_bolsa",
            ),
        ),
    ]
