# Generated by Django 6.0.3 on 2026-09-22 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inscricoes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inscricao",
            name="data_decisao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inscricao",
            name="justificativa_indeferimento",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="inscricao",
            name="responsavel_decisao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inscricoes_analisadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="inscricao",
            name="status",
            field=models.CharField(
                choices=[
                    ("RASCUNHO", "Rascunho"),
                    ("PENDENTE", "Pendente"),
                    ("CANCELADA", "Cancelada"),
                    ("HOMOLOGADA", "Homologada"),
                    ("INDEFERIDA", "Indeferida"),
                ],
                default="RASCUNHO",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="NotificacaoInscricao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("mensagem", models.TextField()),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("lida_em", models.DateTimeField(blank=True, null=True)),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to="inscricoes.inscricao",
                    ),
                ),
            ],
            options={
                "ordering": ["-criada_em", "-id"],
            },
        ),
    ]
