# Generated by Django 6.0.3 on 2026-09-23 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import inscricoes.models


class Migration(migrations.Migration):
    dependencies = [
        ("inscricoes", "0002_homologacao_notificacoes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "etapa",
                    models.CharField(
                        choices=[("HOMOLOGACAO", "Homologação")],
                        default="HOMOLOGACAO",
                        max_length=20,
                    ),
                ),
                ("justificativa", models.TextField()),
                ("motivo_contestado", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("DEFERIDO", "Deferido"),
                            ("INDEFERIDO", "Indeferido"),
                        ],
                        default="PENDENTE",
                        max_length=15,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("julgado_em", models.DateTimeField(blank=True, null=True)),
                ("justificativa_julgamento", models.TextField(blank=True, default="")),
                (
                    "inscricao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recursos",
                        to="inscricoes.inscricao",
                    ),
                ),
                (
                    "responsavel_julgamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recursos_julgados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AnexoRecurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome_original", models.CharField(max_length=255)),
                ("arquivo", models.FileField(upload_to=inscricoes.models.caminho_anexo_recurso)),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="inscricoes.recurso",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="recurso",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PENDENTE")),
                fields=("inscricao", "etapa"),
                name="uniq_recurso_pendente_inscricao_etapa",
            ),
        ),
    ]
