"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()

environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

# SECURITY WARNING: keep the secret key used in production secret!
# Tem que ser igual a SECRET_KEY definida no HUB, é ela que
# assina/verifica o JWT usado pelo fs_auth_middleware
SECRET_KEY = env("SECRET_KEY", default="django-insecure-!@#%$^&*()_+1234567890" if DEBUG else None)
if not SECRET_KEY:
    raise ImproperlyConfigured("Defina SECRET_KEY no .env quando DEBUG=False.")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=["localhost", "127.0.0.1"])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "accounts",
    "hub_integration",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

AUTH_USER_MODEL = "accounts.Usuario"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.authentication.HubJWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# integração com o HUB (fs_auth_middleware)
AUTH_COOKIE_NAME = env("AUTH_COOKIE_NAME", default="access_token")
REFRESH_COOKIE_NAME = env("REFRESH_COOKIE_NAME", default="refresh_token")
FS_AUTH_SYSTEM_MODEL = "hub_integration.System"

# base da API do HUB, para chamadas servidor-a-servidor
HUB_BASE_URL = env("HUB_BASE_URL", default="http://localhost:8000")

# dados do registro deste sistema no HUB (usados por `seed_hub_system`).
HUB_SYSTEM_ID = env("HUB_SYSTEM_ID", default=None)
HUB_SYSTEM_NAME = env("HUB_SYSTEM_NAME", default="Sistema-de-Bolsistas")
HUB_SYSTEM_URL = env("HUB_SYSTEM_URL", default="http://localhost:8001")
HUB_SYSTEM_API_KEY = env("HUB_SYSTEM_API_KEY", default=None)
HUB_SYSTEM_SECRET_KEY = env("HUB_SYSTEM_SECRET_KEY", default=None)

# email dos coordenadores da area, por enquanto definidos no .env mas futuramente teremos uma funcionalidade para isso
COORDENADOR_AREA_EMAILS = {
    "ENSINO": env("COORDENADOR_ENSINO_EMAIL", default=""),
    "PESQUISA": env("COORDENADOR_PESQUISA_EMAIL", default=""),
    "EXTENSAO": env("COORDENADOR_EXTENSAO_EMAIL", default=""),
}

CORS_ALLOWED_ORIGINS = env.list(
    "CORS_ALLOWED_ORIGINS",
    default=["http://localhost:5173", "http://127.0.0.1:5173"],
)
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR.parent / "client" / "dist"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "server.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "assets/"

STATICFILES_DIRS = [
    BASE_DIR.parent / "client" / "dist" / "assets",
]
