# Generated by Django 6.0.3 on 2026-09-17 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_emailcoordenadorarea"),
        ("editais", "0004_edital_ano_codigo"),
        ("projetos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bolsa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENSINO", "Ensino"),
                            ("PESQUISA", "Pesquisa"),
                            ("EXTENSAO", "Extensão"),
                            ("INDISSOCIAVEL", "Indissociável"),
                        ],
                        help_text="Define qual Coordenador de Área aprova/rejeita esta bolsa.",
                        max_length=20,
                    ),
                ),
                (
                    "modalidade",
                    models.CharField(
                        choices=[
                            ("BICT", "Bolsa de Iniciação Científica"),
                            (
                                "BIDTI",
                                "Bolsa de Iniciação ao Desenvolvimento Tecnológico e Inovação",
                            ),
                            ("BAT", "Bolsa de Apoio Técnico"),
                        ],
                        max_length=10,
                    ),
                ),
                ("carga_horaria_semanal", models.PositiveIntegerField()),
                (
                    "valor_mensal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Placeholder — no futuro será calculado a partir de modalidade + carga horária.",
                        max_digits=10,
                    ),
                ),
                ("prerequisitos", models.TextField(blank=True, default="")),
                ("metodologia_avaliacao", models.TextField(blank=True, default="")),
                (
                    "nota_minima",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                ("data_inicio_vigencia", models.DateField(blank=True, null=True)),
                ("data_fim_vigencia", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SOLICITADA", "Solicitada"),
                            ("APROVADA", "Aprovada"),
                            ("REJEITADA", "Rejeitada"),
                            ("ABERTA", "Aberta"),
                            ("EM_SELECAO", "Em Seleção"),
                            ("PREENCHIDA", "Preenchida"),
                            ("ENCERRADA", "Encerrada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="SOLICITADA",
                        max_length=15,
                    ),
                ),
                ("data_solicitacao", models.DateTimeField(auto_now_add=True)),
                ("data_decisao", models.DateTimeField(blank=True, null=True)),
                ("justificativa_decisao", models.TextField(blank=True, default="")),
                (
                    "coordenador_area",
                    models.ForeignKey(
                        blank=True,
                        help_text="Coordenador de Área que aprovou/rejeitou esta bolsa.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bolsas_avaliadas",
                        to="accounts.coordenadorarea",
                    ),
                ),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bolsas",
                        to="editais.edital",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bolsas",
                        to="projetos.projeto",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_solicitacao"],
            },
        ),
    ]
