# Generated by Django 6.0.3 on 2026-09-17 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editais', '0004_edital_ano_codigo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('BICT', 'Bolsa de Iniciação Científica'), ('BIDTI', 'Bolsa de Iniciação ao Desenvolvimento Tecnológico e Inovação'), ('BAT', 'Bolsa de Apoio Técnico')], max_length=10)),
                ('carga_horaria_semanal', models.PositiveIntegerField()),
                ('valor_mensal', models.DecimalField(decimal_places=2, default=0, help_text='Placeholder — será preenchido pela tabela do edital futuramente', max_digits=10)),
                ('prerequisitos', models.TextField(blank=True, default='')),
                ('nota_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('data_avaliacao', models.DateField(blank=True, null=True)),
                ('data_inicio_vigencia', models.DateField(blank=True, null=True)),
                ('data_fim_vigencia', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('DEFERIDA', 'Deferida'), ('INDEFERIDA', 'Indeferida'), ('CANCELADA', 'Cancelada')], default='SOLICITADA', max_length=15)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_decisao', models.DateTimeField(blank=True, null=True)),
                ('justificativa_decisao', models.TextField(blank=True, default='')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bolsas', to='editais.edital')),
                ('solicitante', models.ForeignKey(help_text='Coordenador de Projeto que solicitou a bolsa', on_delete=django.db.models.deletion.PROTECT, related_name='bolsas_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
