# Generated by Django 6.0.3 on 2026-09-27 16:19

import django.core.validators
from django.db import migrations, models

import bolsas.models


class Migration(migrations.Migration):
    dependencies = [
        ("bolsas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bolsa",
            name="arquivo_ementa",
            field=models.FileField(
                blank=True,
                default="",
                help_text="Matriz curricular / ementa da bolsa.",
                upload_to=bolsas.models.caminho_arquivo_bolsa,
                validators=[django.core.validators.FileExtensionValidator(["pdf", "doc", "docx"])],
            ),
        ),
        migrations.AddField(
            model_name="bolsa",
            name="nome_original_arquivo",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="bolsa",
            name="quantidade_vagas",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Quantidade de vagas (titulares) ofertadas nesta bolsa.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
