# Generated by Django 6.0.3 on 2026-09-27 17:05

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bolsas", "0002_bolsa_arquivo_ementa_bolsa_nome_original_arquivo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EtapaAvaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "peso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso da etapa em %. Vazio = divide igualmente o que sobra de 100%.",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "bolsa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="etapas",
                        to="bolsas.bolsa",
                    ),
                ),
            ],
            options={
                "verbose_name": "etapa de avaliação",
                "verbose_name_plural": "etapas de avaliação",
                "ordering": ["id"],
            },
        ),
    ]
