# Generated by Django 6.0.3 on 2026-09-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bolsas", "0003_etapaavaliacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="etapaavaliacao",
            name="data_hora",
            field=models.DateTimeField(
                blank=True, help_text="Data e hora em que a etapa acontece.", null=True
            ),
        ),
        migrations.AddField(
            model_name="etapaavaliacao",
            name="local",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Local (ex.: Sala 204) ou link da reunião online.",
                max_length=255,
            ),
        ),
    ]
