# Generated by Django 6.0.3 on 2026-09-27 21:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bolsas", "0004_etapaavaliacao_data_hora_etapaavaliacao_local"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bolsa",
            name="arquivo_ementa",
        ),
        migrations.RemoveField(
            model_name="bolsa",
            name="nome_original_arquivo",
        ),
    ]
