# Generated by Django 6.0.3 on 2026-09-29 08:27

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_historicalcoordenadorarea_and_more"),
        ("bolsas", "0005_remove_bolsa_arquivo_ementa_and_more"),
        ("editais", "0006_edital_dia_limite_frequencia_historicaledital"),
        ("projetos", "0003_historicalprojeto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalBolsa",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENSINO", "Ensino"),
                            ("PESQUISA", "Pesquisa"),
                            ("EXTENSAO", "Extensão"),
                            ("INDISSOCIAVEL", "Indissociável"),
                        ],
                        help_text="Define qual Coordenador de Área aprova/rejeita esta bolsa.",
                        max_length=20,
                    ),
                ),
                (
                    "modalidade",
                    models.CharField(
                        choices=[
                            ("BICT", "Bolsa de Iniciação Científica"),
                            (
                                "BIDTI",
                                "Bolsa de Iniciação ao Desenvolvimento Tecnológico e Inovação",
                            ),
                            ("BAT", "Bolsa de Apoio Técnico"),
                        ],
                        max_length=10,
                    ),
                ),
                ("carga_horaria_semanal", models.PositiveIntegerField()),
                (
                    "valor_mensal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Placeholder — no futuro será calculado a partir de modalidade + carga horária.",
                        max_digits=10,
                    ),
                ),
                (
                    "quantidade_vagas",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Quantidade de vagas (titulares) ofertadas nesta bolsa.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("prerequisitos", models.TextField(blank=True, default="")),
                ("metodologia_avaliacao", models.TextField(blank=True, default="")),
                (
                    "nota_minima",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
                ),
                ("data_inicio_vigencia", models.DateField(blank=True, null=True)),
                ("data_fim_vigencia", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SOLICITADA", "Solicitada"),
                            ("APROVADA", "Aprovada"),
                            ("REJEITADA", "Rejeitada"),
                            ("ABERTA", "Aberta"),
                            ("EM_SELECAO", "Em Seleção"),
                            ("PREENCHIDA", "Preenchida"),
                            ("ENCERRADA", "Encerrada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="SOLICITADA",
                        max_length=15,
                    ),
                ),
                ("data_solicitacao", models.DateTimeField(blank=True, editable=False)),
                ("data_decisao", models.DateTimeField(blank=True, null=True)),
                ("justificativa_decisao", models.TextField(blank=True, default="")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "coordenador_area",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Coordenador de Área que aprovou/rejeitou esta bolsa.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.coordenadorarea",
                    ),
                ),
                (
                    "edital",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="editais.edital",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projetos.projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical bolsa",
                "verbose_name_plural": "historical bolsas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEtapaAvaliacao",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "peso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso da etapa em %. Vazio = divide igualmente o que sobra de 100%.",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(
                        blank=True, help_text="Data e hora em que a etapa acontece.", null=True
                    ),
                ),
                (
                    "local",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Local (ex.: Sala 204) ou link da reunião online.",
                        max_length=255,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "bolsa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bolsas.bolsa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical etapa de avaliação",
                "verbose_name_plural": "historical etapas de avaliação",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
