# Generated by Django 6.0.3 on 2026-09-29 08:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bolsas", "0006_historicalbolsa_historicaletapaavaliacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalVinculoBolsista",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ATIVO", "Ativo"), ("DESLIGADO", "Desligado")],
                        default="ATIVO",
                        max_length=10,
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"role": "ALUNO"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bolsa",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bolsas.bolsa",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vínculo de bolsista",
                "verbose_name_plural": "historical vínculos de bolsistas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VinculoBolsista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ATIVO", "Ativo"), ("DESLIGADO", "Desligado")],
                        default="ATIVO",
                        max_length=10,
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        limit_choices_to={"role": "ALUNO"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vinculos_bolsista",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bolsa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vinculos",
                        to="bolsas.bolsa",
                    ),
                ),
            ],
            options={
                "verbose_name": "vínculo de bolsista",
                "verbose_name_plural": "vínculos de bolsistas",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalFrequencia",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "mes_referencia",
                    models.DateField(
                        help_text="Primeiro dia do mês de referência (ex.: 2026-09-01 para setembro/2026)."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("INFORMADA", "Informada"),
                            ("NAO_INFORMADA", "Não Informado"),
                        ],
                        default="PENDENTE",
                        max_length=15,
                    ),
                ),
                ("lancada_em", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lancada_por",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vinculo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bolsas.vinculobolsista",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical frequência mensal",
                "verbose_name_plural": "historical frequências mensais",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Frequencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "mes_referencia",
                    models.DateField(
                        help_text="Primeiro dia do mês de referência (ex.: 2026-09-01 para setembro/2026)."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("INFORMADA", "Informada"),
                            ("NAO_INFORMADA", "Não Informado"),
                        ],
                        default="PENDENTE",
                        max_length=15,
                    ),
                ),
                ("lancada_em", models.DateTimeField(blank=True, null=True)),
                (
                    "lancada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="frequencias_lancadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vinculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="frequencias",
                        to="bolsas.vinculobolsista",
                    ),
                ),
            ],
            options={
                "verbose_name": "frequência mensal",
                "verbose_name_plural": "frequências mensais",
                "ordering": ["-mes_referencia"],
                "unique_together": {("vinculo", "mes_referencia")},
            },
        ),
    ]
