# Generated by Django 6.0.3 on 2026-09-15 03:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Edital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome do edital (mínimo de 3 caracteres)",
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "ano_semestre",
                    models.CharField(help_text="Ano e semestre (ex: 2022/1)", max_length=6),
                ),
                (
                    "link_documento_oficial",
                    models.URLField(
                        help_text="Link para o documento oficial do edital", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("EM_VIGOR", "Em vigor"),
                            ("ENCERRADO", "Encerrado"),
                            ("ARQUIVADO", "Arquivado"),
                        ],
                        default="RASCUNHO",
                        help_text="Status do edital",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
