# Generated by Django 6.0.3 on 2026-09-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="edital",
            name="data_abertura_inscricoes",
            field=models.DateField(
                blank=True, help_text="Data de abertura das inscrições", null=True
            ),
        ),
        migrations.AddField(
            model_name="edital",
            name="data_entrega_relatorios",
            field=models.DateField(
                blank=True, help_text="Data de entrega dos relatórios finais", null=True
            ),
        ),
        migrations.AddField(
            model_name="edital",
            name="data_fechamento_inscricoes",
            field=models.DateField(
                blank=True, help_text="Data de fechamento das inscrições", null=True
            ),
        ),
        migrations.AddField(
            model_name="edital",
            name="data_homologacao",
            field=models.DateField(
                blank=True, help_text="Data de homologação do edital", null=True
            ),
        ),
        migrations.AddField(
            model_name="edital",
            name="data_recurso_homologacao_fim",
            field=models.DateField(
                blank=True, help_text="Data de fim dos recursos de homologação", null=True
            ),
        ),
        migrations.AddField(
            model_name="edital",
            name="data_recurso_homologacao_inicio",
            field=models.DateField(
                blank=True, help_text="Data de início dos recursos de homologação", null=True
            ),
        ),
        migrations.AddField(
            model_name="edital",
            name="data_resultado",
            field=models.DateField(
                blank=True, help_text="Data de divulgação do resultado final", null=True
            ),
        ),
    ]
