# Generated by Django 6.0.3 on 2026-09-16 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0002_edital_data_abertura_inscricoes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlteracaoCronograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("campo", models.CharField(max_length=50)),
                ("data_anterior", models.DateField(blank=True, null=True)),
                ("data_nova", models.DateField(blank=True, null=True)),
                ("alterado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "edital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="historico_cronograma",
                        to="editais.edital",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alteracoes_cronograma",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-alterado_em", "-id"],
            },
        ),
    ]
