# Generated by Django 6.0.3 on 2026-09-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0004_edital_ano_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="edital",
            name="data_maxima_preenchimento_vagas",
            field=models.DateField(
                blank=True, help_text="Data máxima para preenchimento das vagas", null=True
            ),
        ),
    ]
