# Generated by Django 6.0.3 on 2026-09-29 08:27

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editais", "0005_edital_data_maxima_preenchimento_vagas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="edital",
            name="dia_limite_frequencia",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Dia do mês limite para o Coordenador de Projeto lançar a frequência (1–31).",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalEdital",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Nome do edital (mínimo de 3 caracteres)",
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "ano_codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Ano e código do edital (ex: 2026-005)",
                        max_length=8,
                    ),
                ),
                (
                    "link_documento_oficial",
                    models.URLField(
                        help_text="Link para o documento oficial do edital", max_length=500
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RASCUNHO", "Rascunho"),
                            ("EM_VIGOR", "Em vigor"),
                            ("ENCERRADO", "Encerrado"),
                            ("ARQUIVADO", "Arquivado"),
                        ],
                        default="RASCUNHO",
                        help_text="Status do edital",
                        max_length=10,
                    ),
                ),
                (
                    "data_abertura_inscricoes",
                    models.DateField(
                        blank=True, help_text="Data de abertura das inscrições", null=True
                    ),
                ),
                (
                    "data_fechamento_inscricoes",
                    models.DateField(
                        blank=True, help_text="Data de fechamento das inscrições", null=True
                    ),
                ),
                (
                    "data_homologacao",
                    models.DateField(
                        blank=True, help_text="Data de homologação do edital", null=True
                    ),
                ),
                (
                    "data_recurso_homologacao_inicio",
                    models.DateField(
                        blank=True,
                        help_text="Data de início dos recursos de homologação",
                        null=True,
                    ),
                ),
                (
                    "data_recurso_homologacao_fim",
                    models.DateField(
                        blank=True, help_text="Data de fim dos recursos de homologação", null=True
                    ),
                ),
                (
                    "data_resultado",
                    models.DateField(
                        blank=True, help_text="Data de divulgação do resultado final", null=True
                    ),
                ),
                (
                    "data_maxima_preenchimento_vagas",
                    models.DateField(
                        blank=True, help_text="Data máxima para preenchimento das vagas", null=True
                    ),
                ),
                (
                    "data_entrega_relatorios",
                    models.DateField(
                        blank=True, help_text="Data de entrega dos relatórios finais", null=True
                    ),
                ),
                (
                    "dia_limite_frequencia",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Dia do mês limite para o Coordenador de Projeto lançar a frequência (1–31).",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical edital",
                "verbose_name_plural": "historical editals",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
