# Generated by Django 6.0.3 on 2026-09-17 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_emailcoordenadorarea"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("ATIVO", "Ativo"), ("DESLIGADO", "Desligado")],
                        default="ATIVO",
                        max_length=15,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "coordenador_projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projetos",
                        to="accounts.coordenadorprojeto",
                    ),
                ),
            ],
            options={
                "ordering": ["-criado_em"],
            },
        ),
    ]
