# Generated by Django 6.0.3 on 2026-09-27 21:37

import django.core.validators
from django.db import migrations, models

import projetos.models


class Migration(migrations.Migration):
    dependencies = [
        ("projetos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projeto",
            name="arquivo_ementa",
            field=models.FileField(
                blank=True,
                default="",
                help_text="Matriz curricular / ementa do projeto.",
                upload_to=projetos.models.caminho_arquivo_ementa,
                validators=[django.core.validators.FileExtensionValidator(["pdf", "doc", "docx"])],
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="nome_original_arquivo",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
