# Generated by Django 6.0.3 on 2026-09-29 08:27

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_historicalcoordenadorarea_and_more"),
        ("projetos", "0002_projeto_arquivo_ementa_projeto_nome_original_arquivo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalProjeto",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("ATIVO", "Ativo"), ("DESLIGADO", "Desligado")],
                        default="ATIVO",
                        max_length=15,
                    ),
                ),
                (
                    "arquivo_ementa",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Matriz curricular / ementa do projeto.",
                        max_length=100,
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf", "doc", "docx"])
                        ],
                    ),
                ),
                ("nome_original_arquivo", models.CharField(blank=True, default="", max_length=255)),
                ("criado_em", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "coordenador_projeto",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="accounts.coordenadorprojeto",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical projeto",
                "verbose_name_plural": "historical projetos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
