# Generated by Django 6.0.3 on 2026-09-09 02:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="System",
            fields=[
                ("id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("system_url", models.URLField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("api_key", models.CharField(max_length=255)),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("Em desenvolvimento", "Em desenvolvimento"),
                            ("Implantado", "Implantado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("secret_key", models.CharField(max_length=200)),
                ("dev_team", models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
